#  GitHub Actions Python V2zc1.0@sw586 - 2020/07/21 6

name: jafiyun.cc_Python-V2ZC-Actions

on:
  watch:
    types: started
  push:
    branches: [ master ]
  schedule:
#    - cron: '0 */1 * * *'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
         fetch-depth: 2
         python-version: 3.8
    - name: Install dependencies
      run: |
         python -m pip install --upgrade pip
         pip install flake8 pytest
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run
      run: python zc.py
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: vhost264.cloudvhost.cn
        username: webmaster@HA434896
        password: IUpoQbjCd568roPi
        server-dir: /WEB/
        exclude: .git*
          - .git*/**
          -  **/.git*/**
          - zc.py
          - in.php
          - README.md
          - .git-ftp.log
          - .ftp-deploy-sync-state.json
          - requirements.txt
          - .github/**
          - .idea/**
    - name: inphp
      run: curl https://sw.qiji.pw/in.php
# - name: SSH connection to Actions
# uses: P3TERX/debugger-action@master    
# run: touch /tmp/keepalive
